import type { SoundMeta } from '../types';
import { SoundMixer } from '../mixer';

/**
 * UI Controls — renders sound cards, sliders, and master controls.
 * Single Responsibility: only DOM rendering and event binding.
 * All logic is delegated to the SoundMixer.
 */
export class Controls {
  private readonly container: HTMLElement;
  private readonly activeSoundscapes = new Set<string>();

  constructor(
    private readonly mixer: SoundMixer,
    private readonly sounds: SoundMeta[],
    private readonly onStateChange: () => void,
    private readonly compositions: Record<string, { id: string; volume: number }[]> = {},
  ) {
    this.container = document.getElementById('app')!;
    this.render();
  }

  private render(): void {
    const basicSounds = this.sounds.filter((s) => s.category === 'basic');
    const soundscapes = this.sounds.filter((s) => s.category === 'soundscape');

    this.container.innerHTML = `
      <header class="header">
        <h1>Nois</h1>
        <p>Ambient soundscapes generated by math. Zero audio files.</p>
      </header>

      <div class="visualizer-container">
        <canvas class="visualizer-canvas" id="visualizer"></canvas>
      </div>

      <div class="sound-grid" id="sound-grid">
        <div class="section-label">Basic Sounds</div>
        ${basicSounds.map((s) => this.renderCard(s)).join('')}
        ${soundscapes.length > 0 ? `
          <div class="section-label">Soundscapes</div>
          ${soundscapes.map((s) => this.renderCard(s)).join('')}
        ` : ''}
      </div>

      <div class="master-controls">
        <span class="master-controls__label">Master</span>
        <input type="range" class="master-volume-slider" id="master-volume"
               min="0" max="100" value="${this.mixer.state.masterVolume * 100}" />
        <button class="stop-all-btn" id="stop-all">Stop All</button>
      </div>

      <div class="presets-bar" id="presets-bar">
        <span class="presets-bar__label">Presets</span>
        <button class="save-preset-btn" id="save-preset">+ Save current</button>
      </div>

      <div class="pomodoro-bar" id="pomodoro-bar">
        <div class="pomodoro-bar__controls">
          <button class="pomodoro-btn" id="pomodoro-toggle">Pomodoro</button>
        </div>
        <span class="pomodoro-bar__timer" id="pomodoro-timer" style="display:none">25:00</span>
        <span class="pomodoro-bar__mode" id="pomodoro-mode" style="display:none">Focus</span>
      </div>

      <footer class="footer">
        <p>Nois — every sound is math, every session is unique</p>
      </footer>
    `;

    this.bindEvents();
  }

  private renderCard(meta: SoundMeta): string {
    const state = this.mixer.state.sounds[meta.id];
    const isActive = state?.active ?? false;
    const volume = state?.volume ?? 0.3;

    return `
      <div class="sound-card ${isActive ? 'active' : ''}" data-sound-id="${meta.id}">
        <div class="sound-card__header">
          <span class="sound-card__icon">${meta.icon}</span>
          <span class="sound-card__name">${meta.name}</span>
          <span class="sound-card__status">${isActive ? 'ON' : 'OFF'}</span>
        </div>
        <input type="range" class="volume-slider" data-volume-id="${meta.id}"
               min="0" max="100" value="${volume * 100}" />
      </div>
    `;
  }

  private bindEvents(): void {
    // Sound card clicks
    this.container.querySelectorAll<HTMLElement>('.sound-card').forEach((card) => {
      const id = card.dataset.soundId ?? '';

      card.addEventListener('click', async (e) => {
        // Don't toggle when clicking the slider
        if ((e.target as HTMLElement).classList.contains('volume-slider')) return;

        if (this.compositions[id]) {
          await this.toggleSoundscape(id);
        } else {
          await this.mixer.toggleSound(id);
          this.updateCard(id);
        }
        this.onStateChange();
      });
    });

    // Volume sliders
    this.container.querySelectorAll('.volume-slider').forEach((slider) => {
      const id = (slider as HTMLInputElement).dataset.volumeId ?? '';
      slider.addEventListener('input', (e) => {
        e.stopPropagation();
        const value = Number((e.target as HTMLInputElement).value) / 100;
        this.mixer.setVolume(id, value);
        this.onStateChange();
      });
    });

    // Master volume
    const masterSlider = document.getElementById('master-volume') as HTMLInputElement;
    masterSlider?.addEventListener('input', (e) => {
      const value = Number((e.target as HTMLInputElement).value) / 100;
      this.mixer.setMasterVolume(value);
      this.onStateChange();
    });

    // Stop all
    document.getElementById('stop-all')?.addEventListener('click', () => {
      this.mixer.stopAll();
      this.activeSoundscapes.clear();
      this.updateAllCards();
      this.onStateChange();
    });
  }

  private updateCard(id: string): void {
    const card = this.container.querySelector(`[data-sound-id="${id}"]`);
    if (!card) return;

    const state = this.mixer.state.sounds[id];
    card.classList.toggle('active', state.active);

    const status = card.querySelector('.sound-card__status');
    if (status) status.textContent = state.active ? 'ON' : 'OFF';

    const slider = card.querySelector('.volume-slider') as HTMLInputElement;
    if (slider) slider.value = String(state.volume * 100);
  }

  updateAllCards(): void {
    for (const id of Object.keys(this.mixer.state.sounds)) {
      if (!this.compositions[id]) {
        this.updateCard(id);
      }
    }
    for (const id of Object.keys(this.compositions)) {
      this.updateSoundscapeCard(id);
    }
  }

  private async toggleSoundscape(id: string): Promise<void> {
    const composition = this.compositions[id];
    if (!composition) return;

    const isActive = this.activeSoundscapes.has(id);

    if (isActive) {
      // Turn off all component sounds
      for (const component of composition) {
        if (this.mixer.state.sounds[component.id]?.active) {
          await this.mixer.toggleSound(component.id);
          this.updateCard(component.id);
        }
      }
      this.activeSoundscapes.delete(id);
    } else {
      // Turn on all component sounds with preset volumes
      for (const component of composition) {
        this.mixer.setVolume(component.id, component.volume);
        if (!this.mixer.state.sounds[component.id]?.active) {
          await this.mixer.toggleSound(component.id);
        }
        this.updateCard(component.id);
      }
      this.activeSoundscapes.add(id);
    }

    this.updateSoundscapeCard(id);
  }

  private updateSoundscapeCard(id: string): void {
    const card = this.container.querySelector(`[data-sound-id="${id}"]`);
    if (!card) return;

    const isActive = this.activeSoundscapes.has(id);
    card.classList.toggle('active', isActive);

    const status = card.querySelector('.sound-card__status');
    if (status) status.textContent = isActive ? 'ON' : 'OFF';
  }
}
